name: LinuxDev

on:
  push:
    branches: [ development, linux ]
  pull_request:
    branches: [ development, linux ]
    
jobs:

  build-Ubuntu:
    
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        sudo apt-get install xorg-dev
        cd Dependencies/cpython
        mkdir debug
        cd debug
        ../configure --enable-shared --prefix $PWD
        sudo make && sudo make install
        cd ..
        cd ..
        cd ..
        pip3 install wheel
        pip3 install twine
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..

    - name: Build DearPyGui
      run: |
        cmake --build cmake-build-release --config Release

    - name: Build Test DearPyGui Wheel
      run: |
        cd /home/runner/work/DearPyGui/DearPyGui/Distribution
        python3 BuildPythonWheel.py /home/runner/work/DearPyGui/DearPyGui/cmake-build-release/DearPyGui/dearpygui.so dearpygui.so
        python3 -m setup bdist_wheel --plat-name manylinux1_x86_64 --dist-dir /home/runner/work/DearPyGui/DearPyGui/dist

    - name: Upload Test DearPyGui Wheel
      if: "!contains(github.event.head_commit.message, 'upload skip')"
      run: |
        python3 -m twine upload --repository testpypi dist/* -u __token__ -p ${{ secrets.test_pypi_password }} --skip-existing